-- phpMyAdmin SQL Dump
-- version 4.7.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Apr 26, 2018 at 02:13 PM
-- Server version: 5.6.38
-- PHP Version: 7.2.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: `BTA`
--

-- --------------------------------------------------------

--
-- Table structure for table `attraction`
--

CREATE TABLE `attraction` (
  `attID` int(11) NOT NULL,
  `name` varchar(128) NOT NULL,
  `operDate` varchar(128) NOT NULL,
  `operTime` varchar(256) NOT NULL,
  `suggTime` varchar(256) DEFAULT NULL,
  `cost` varchar(256) DEFAULT NULL,
  `type` varchar(16) NOT NULL,
  `zone` varchar(16) NOT NULL,
  `transportation` varchar(256) DEFAULT NULL,
  `description` text,
  `validated` varchar(1) NOT NULL,
  `imgSrc` varchar(100) NOT NULL,
  `lat` float(10,6) NOT NULL,
  `lng` float(10,6) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `attraction`
--

INSERT INTO `attraction` (`attID`, `name`, `operDate`, `operTime`, `suggTime`, `cost`, `type`, `zone`, `transportation`, `description`, `validated`, `imgSrc`, `lat`, `lng`) VALUES
(1, 'The Grand Palace', 'Everyday', '8:30am - 3:30pm', '2 hours at the morning', '500 Baht for foreigners , Free for locals', 'palace', 'Phranakhon', NULL, 'Explore the famous complex of ornate buildings at The Grand Palace, a gem in the country\'s architectural and political heritage. Established in 1782, the palace grounds have been added to over the centuries with eclectically designed buildings, halls, and pavilions. The official home of Thai monarchs until the abolishment of the absolute monarchy in 1932, the site remains open to visitors, with its well-maintained grounds and monumental architecture providing great photo ops and an immersive cultural experience. ', 'Y', 'the grand palace.jpg', 13.750031, 100.491287),
(2, 'Temple of the Emerald Buddha', 'Everyday', '8:30am – 3:30pm ', '1 hours at the morning', '500 Baht for foreigners , Free for locals', 'temple', 'Phranakhon', NULL, 'Pay a visit to the most sacred Buddhist temple in Thailand at Temple of the Emerald Buddha (Wat Phra Kaew). Located in the precincts of the Grand Palace, the temple houses an emerald Buddha statue carved from semi-precious green stone and covered in gold--deemed to be the palladium (protective image) of Thailand. The surrounding buildings, sculptural forms, and murals complement the regal and spiritual atmosphere of the room in which the Buddha is kept. Take time to wander the grounds, a great place to get lost in.', 'Y', 'watprakaew.jpg', 13.751644, 100.492706),
(3, 'Chatuchak Weekend Market', 'Weekend', '10:00am - 7:00pm', '3h 30 min for sightseeing , 5h-6h for shopaholic', 'Free', 'shopping', 'Chatuchak', NULL, 'Browse the day away at Chatuchak Weekend Market, a popular covered retail space in the city center. Attracting over 200,000 visitors on a typical weekend, the huge market offers 27 separate areas of stalls, with over 8,000 individual vendors plying their trade. From collectibles, souvenirs, and clothes, to fresh food, restaurants, and household appliance stores, the market contains a mind-boggling range of products. Its sheer scale will likely impress even those who have nothing on their shopping list.', 'Y', 'chatuchak.jpg', 13.800113, 100.551041),
(4, 'Siam Paragon', 'Everyday', '10:00am - 10:00pm', '2 hours walking', 'Free', 'shopping', 'Pathumwan', NULL, 'Find what you\'re looking for at Siam Paragon, a modern, upscale shopping mall in Bangkok--and one of the largest in Asia. Since opening in 2008, the center has become a place to be seen for locals and a place to see for tourists: the stylish displays and elite brands on offer here make for an attractive place of commerce and leisure, while modern flourishes neatly encapsulate the will for modernization in the region. With a multitude of shops, international and local restaurants, and a multiplex cinema, the mall offers different experiences for a wide set of visitors.', 'Y', 'paragon.jpg', 13.746091, 100.534813),
(5, 'Temple of Dawn (Wat Arun)', 'Everyday', '8:00am - 5.30pm', '1 hours walking', '50 Baht for foreigners, Free for locals', 'temple', 'Chaopraya', NULL, 'Admire the grand and evocative design of Temple of Dawn (Wat Arun), a towering Buddhist temple located in the heart of Bangkok. Established in the 1600s--but gaining its distinctive porcelain-clad prangs (spires) during the reign of King Rama II in the early 19th century--the temple represents an apex of religious architecture and is one of the best maintained of all buildings commissioned by the Thai monarchy. Open to the public as a place of worship and tourism, the site contains prized artifacts relating to the religious and royal history of Thailand. ', 'Y', 'wat arun.jpeg', 13.743685, 100.488930),
(6, 'MBK Center (Ma Boon Khrong Center)', 'Everyday', '10:00am - 10:00pm', '3 hours walking, a day for shopping', 'Free', 'shopping', 'Pathumwan', NULL, 'Feel the buzz of commerce in the capital at MBK Center (Ma Boon Khrong Center), an enormous shopping mall in the heart of Bangkok. Popular with tourists and locals alike, the entire complex houses around 2,000 businesses offering a variety of products and services. The elevated walkways and throngs of people make this a popular tourist destination even for those not initially interested in purchasing anything. Visit the center to take a photo or two, and browse around to see if anything catches your eye.', 'Y', 'mbk.jpg', 13.744468, 100.529907),
(7, 'Safari World', 'Everyday', '9:00am - 5:00pm', '5 hours for visiting, a day for passion', 'Safari Park : Adult = 1,000 Baht , Child = 900 Baht;\r\nMarine Park : Adult = 1,200 Baht , Child = 1,000 Baht;\r\nBoth Park : Adult = 1,400 Baht , Child = 1,100 Baht;  ', 'other', 'Khlong Sam Wa', 'NULL', 'A trip around the huge grounds of Safari World guarantees sights of a range of animals in a safari experience. You can use your own car or go on an official tour to see the creatures in expansive settings. This \"zoo-plus\" features a large marine environment, bird cages, and even the chance to feed giraffes. Note that there have been many reports of poor treatment of animals here. ', 'Y', 'safari world.jpg', 13.865491, 100.703407),
(8, 'The National Museum Bangkok', 'Wednesday - Sunday', '9:00am - 4:00pm', '1 hours for visiting', '200 Baht for foreigners', 'Museum', 'Phranakhon', NULL, 'Go on a journey through thousands of years of Thai history and culture at The National Museum Bangkok, a treasure chest housed inside the former palace of Siamese viceroys. Originally established in 1874 by King Rama V to showcase his father\'s private collection of artwork, the museum now ranks among the largest in Southeast Asia and displays various aspects of Thai heritage. You can admire everything from precious stones to ornamental clothes, and from prehistoric artifacts to royal thrones. In addition to the rich Thai collection, the museum displays objects from other parts of Southeast Asia and China, including weapons, sculptures, and musical instruments. Information in English and multilingual tours provide context for visitors without knowledge of the Thai language. ', 'Y', 'national museum.JPG', 13.759172, 100.494026),
(9, 'Wat Pho', 'Everyday', 'All Time', '1 hours for visiting', 'Free', 'Temple', 'Phranakhon', NULL, 'Visit Wat Pho, one of the six main Buddhist temples in Thailand. Admire the 46 m (151 ft) long Buddha statue and its memorable pose, and explore the wide range of temple buildings displaying rich and intricate religious designs and a history dating back to the 16th century. Vital to the spiritual and architectural heritage of the city and the country at large, the site houses the largest collection of Buddha depictions in Thailand. Said to be the first public university in the nation, the temple also has an illustrious educational history and still runs courses on traditional Thai massage and medicine. ', 'Y', 'wat pho.jpg', 13.746493, 100.492592),
(10, 'China Town (Yaowarat)', 'Everyday', 'Lunch and Dinner', 'Evening (Dinner)', 'Free', 'Street', 'Phranakhon', NULL, 'Chinatown is a colourful, exotic and pleasingly chaotic area, packed with market stalls and probably the highest concentration of gold shops in the city. During major festivities like Chinese New Year and the Vegetarian Festival, the dynamism and spirit of celebration spreads across town like wildfire, and if you happen to be around, don’t miss an opportunity to witness Bangkok Chinatown at its best.', 'Y', 'yaowarat.jpg', 13.741273, 100.508163),
(11, 'Khao San Road', 'Everyday', 'Evening', 'After Evening', 'Free', 'Street', 'Phranakhon', NULL, 'If Bangkok is a city where East greets West, then Khao San Road is the scene of their collision, the place where they jostle for superiority and poke one another in the eye. With travellers from every corner of the modern world, sleek clubs playing sophisticated sounds, eclectic market stalls, converted VW cocktail bars, and foods tamed to suit the Western palate, it may seem clear who won the fight.', 'Y', 'khao san.jpg', 13.758937, 100.497215),
(12, 'Asiatique The Riverfront', 'EveryDay', '5:00PM - 12:00AM', 'After 7:00PM', 'Free', 'street', 'Chaopraya', NULL, 'Asiatique has successfully combined two of the most popular shopping experiences in the city: a night bazaar and a mall. Ten minutes downriver from Saphan Taksin BTS station this once-bustling international trade port has been transformed, with over 1,500 boutiques and 40 restaurants housed under a huge replica warehouse complex. Open from 17:00, spending an evening here is no problem: you’ll have good fun browsing the boutiques, picking up gifts or something for yourself; you are guaranteed to find something you would like to eat and if this isn’t enough entertainment, shows are performed nightly: Calypso ladyboy cabaret and soon, a classic Thai puppets performance.', 'Y', 'Asiatique.jpg', 13.704704, 100.502640),
(13, 'Lhong 1919', 'EveryDay', '10:00AM - 10:00PM', 'Evening', 'Free', 'street', 'Chaopraya', NULL, 'Lhong 1919 Bangkok is a 19th century Chinese mansion that has been fully restored and opened as an attraction. It mixes Bangkok heritage with shopping, dining and lots of interesting photo opportunities – it ticks all the boxes for a fun day out in Bangkok. The centre point of this old Chinese manor is the large shrine to Mazu, the Chinese goddess of seafarers. The air is heavy with the scent of incense and smoke and many people will kneel to say a prayer. As you walk around the courtyard and rooms, you can see period fixtures and artefacts displayed for visitors to see. In parts, it feels a little like a theme park recreation of what a 19th century Chinese mansion should be, but it’s still wildly popular with locals and visitors.', 'Y', 'lhong 1919.jpg', 13.734309, 100.507637),
(15, 'Jim Thompson\'s House', 'Everyday', '9:00AM - 5:00PM', 'After Afternoon', '100 Baht for Adults, 50 Baht for Students', 'other', 'Pathumwan', NULL, 'The historic home of a \'self-made American entrepreneur\' who disappeared while traveling in Malaysia now stands as a relic of an older time in Bangkok. Jim Thompson settled in Thailand after spending time there as a serviceman around the end of WWII. He was a prominent figure in the Thai silk industry and was awarded the Order of the White Elephant, a significant honor given to foreigners who have made contributions to Thailand. Thompson\'s home has been turned into a museum offering insights into his life and business, as well as the history of the city and the Thai silk industry.', 'Y', 'jim thompson.jpg', 13.749155, 100.528381),
(16, 'Lumpini Park', 'Everyday', '9:00AM - 5:00PM', 'At the early morning', 'Free', 'Park', 'Silom', NULL, 'Lumpini Park provides visitors with a green oasis amidst the traffic and chaos of Bangkok. Hang out on one of several lawn areas, enjoy the shade of a Chinese pagoda, or take a boat out on the lake. Lumpini Park is a great place to spend an afternoon enjoying the contrast of the tranquil park with the skyscrapers rising all around it. Note that the park has been the site of anti-government protests that have occasionally turned violent in the past, so be sure to check on the current status before visiting.', 'Y', 'lumphini.jpg', 13.729922, 100.541336),
(17, 'Terminal 21', 'Everyday', '10:00AM - 10:00PM', 'Meal Time', 'Free', 'Shopping', 'Watthana', NULL, 'The name might lead you to think this is a transport hub, but it\'s actually a shopping mall. And you might be wondering why you would want to visit a shopping mall for kick while traveling. Well, Terminal 21 has a special flair - even by Thailand\'s shopping standards. Every floor of the mall has been themed to a different international city. Enter at the level of the BTS station and you\'ll be in Paris; go up a floor and it\'s Tokyo; another floor and you\'re staring at the iconic red phone booths of London. The Caribbean, San Francisco, and Istanbul also figure into the design theme.', 'Y', 'terminal21.jpg', 13.737877, 100.560440),
(18, 'Central World', 'Everyday', '10:30AM - 10:00PM', 'Any Time', 'Free', 'Shopping', 'Pathumwan', NULL, 'Opened in 1990, the eight-story CentralWorld marketed itself as a middle class shopping center, opposed to the upper class-marketed Siam Paragon. On 19th May 2010, CentralWorld was one of the many properties set on fire by anti government protestors. The fire raged for two days and the Zen department store collapsed in the fire. After months of repair works, the shopping complex reopened on 28th September with 80% of its retail space open for business.', 'Y', 'centralworld.jpg', 13.746539, 100.539360),
(19, 'Platinum Mall', 'Everyday', '8:00AM - 8:00PM', 'Any Time', 'Free', 'Shopping', 'Ratchathewi', NULL, 'The Platinum Mall is a fashion mall; this means the focus of the stores is on fashion and clothing. The mall is ideally located in one of the busiest areas of Bangkok and the 6 storey shopping center caters to bargain hunters and those looking for cheap merchandise. Platinum is a wholesale mall with many clothing, shoe and accessory stores as well as restaurants and a food', 'Y', 'platinum.jpg', 13.750203, 100.539452),
(20, 'Erawan Shrine', 'Everyday', '6:00AM - 6:00AM', '1 hours for visiting', 'Free', 'temple', 'Pathumwan', NULL, 'The Thao Maha Brahma Shrine or Erawan Shrine was constructed in 1956 to appease the Gods/spirits/evil forces when the Grand Hyatt Erawan Hotel building site faced a number of setbacks. The superstitious construction workers refused to continue working until astrologists were consulted and the land spirits were appeased. Believers felt that the bad luck suffered by the construction workers was due to the work beginning on an unfavorable date. The construction of this shrine shows the power of religion in the modern Thai society, and that the many ancient temples and shrines are not just part of the Thai history but a living element in the Thai culture. Once the shrine had been built the deaths stopped and the hotel went on to enjoy 30 years of prosperity!', 'Y', 'erawan.jpg', 13.744397, 100.540367),
(21, 'Museum of Siam', 'Tuesday - Sunday', '10:00AM - 6:00PM', '1 hours for visiting', '300 Baht for foreigners , 100 Baht for locals', 'Museum', 'Phranakhon', NULL, 'This museum shows the development and history of the Thai culture, innovative interactive displays, games and storytelling techniques were used in the museum. The museum building is a neoclassical house, once the Commerce Ministry building. As you approach the museum there is a modern metal sculpture of a coiling ribbon (as used in traditional Thai dancing) on the lawn. On the ribbon is written \'What does it mean to be Thai?\' which captures the museum\'s premise in a nutshell. The ribbon or \'roong\' theme continues throughout the museum.', 'Y', 'museum of siam.jpg', 13.744147, 100.494141),
(22, 'Dusit Zoo', 'Tuesday - Sunday', '8:00AM - 6:00PM', '2 hours for visiting, half a day for passion', '150 Baht for foreigners : 100 Baht for locals', 'other', 'Dusit', NULL, 'Animals from far and wide are featured at Dusit Zoo. Different types of monkeys, hippopotamus, alligators, tigers, and lions together with rare breeds (for Thailand) such as penguins, camels, wallabies, and kangaroos are kept here. Some other highlights include African Savanna, an area where giraffes, ostriches, and zebras roam, Nocturnal House, Reptile House, Pheasants Aviary, Hawks Exhibit, Elephants House, and an impressive Play Land, where many rides are available for your children\'s laughs and giggles.', 'Y', 'dusit zoo.jpg', 13.773880, 100.516182),
(23, 'Chulalongkorn University', 'Everyday', 'All day', 'Any time', 'Free', 'Other', 'Pathumwan', 'BTS Siam, MRT Samyan', 'University in Bangkok', 'Y', 'chulalonglornunisersity.jpg', 13.739007, 100.527611),
(27, 'Bangkok Christian College', 'Everyday', 'All day', 'Any time', 'Free', 'Other', 'Sathorn', 'BTS Surasak', 'Best school in Bangkok', 'Y', 'images.jpeg', 13.721303, 100.522423),
(28, 'Tha Maharaj', 'Everyday', '10.00AM-10.00PM', 'After 7:00PM', 'Free', 'shopping', 'Phranakhon', NULL, '“Tha Maharaj” is located on Maharaj road in Rattanakosin Island, built in the early Ratttanakosin period.  Located on the bank of the Chao Phraya river, Tha Maharaj is surrounded by rich cultural heritage and tourist attraction of Thai arts, museums, The Grand Palace, Wat Pho, Wat Arun The Temple of Dawn, Thammasat University, Silapakorn Fine Arts University, and Siriraj Hospital.  Tourists visit this area daily as their “Must See Place” in Bangkok.  Local visitors also flock this area to experience one of the biggest talisman and amulet market in Thailand.', 'Y', 'thamaharat.jpeg', 13.753642, 100.488823),
(29, 'Phra Sumen Fort', 'Everyday', 'All day', '30 minutes for visiting', 'Free', 'Park', 'Chaopraya', NULL, 'Phra Sumen Fort, in particular, is a sight to behold. Present since 1782 around the time of Bangkok’s founding, the durable fort is one of two last remaining original forts that were built to protect the city from invasions. It is named after Mount Meru in Hindu, Jain, and Buddhist cosmology. The octagonal white brick and stucco structure is three floors high and once housed weapons and ammunition. Today, one can observe canons overlooking the area from the fort still doing their job with vigilance.', 'Y', 'prasumen.jpg', 13.763978, 100.495766),
(30, 'Pipit Banglamphu', 'Tuesday - Sunday', '10.00AM-6.00PM', '1.5 hours for visiting', 'Free', 'Museum', 'Chaopraya', NULL, 'Pipit Bang Lamphu Museum is composed of two L-shaped buildings. The buildings were constructed in 1925 and once served as the Wat Sangwet Printing School. The museum presents local ways of life, historical sites and traditions of the Bang Lamphu community.', 'Y', 'pipit.jpeg', 13.763534, 100.496452),
(36, 'Central Rama III', 'e', 'e', 'e', 'free', 'Shopping', 'rama 3', 'eee', 'eeeee', 'Y', 'bangkok-on-a-budget.jpg', 13.697567, 100.537582);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `attraction`
--
ALTER TABLE `attraction`
  ADD PRIMARY KEY (`attID`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `attraction`
--
ALTER TABLE `attraction`
  MODIFY `attID` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38;
